name: Release

on: [workflow_dispatch]

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  # setting this should create the npmrc with $NODE_AUTH_TOKEN
                  registry-url: 'https://registry.npmjs.org'

            - name: Config git user
              run: |
                  git config --global user.name "${{ github.actor }}"
                  git config --global user.email "${{ github.actor }}@users.noreply.github.com"

            - name: Bootstrap lerna
              run: yarn bootstrap

            - name: Lerna build
              run: yarn build

            - name: Bump versions
              run: yarn version:ci
              env:
                  GH_TOKEN: ${{ secrets.GH_NODE_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

            - name: Publish packages
              if: ${{ env.NODE_AUTH_TOKEN }}
              run: yarn publish:ci
              env:
                  GH_TOKEN: ${{ secrets.GH_NODE_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
